
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alex Wolf
 */
public class JCurrencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form JCurrencyConverter
     */
    public JCurrencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtAmountConverted = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jToCurrency = new javax.swing.JComboBox<>();
        jFromCurrency = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jbtnConverter1 = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Amount Converted");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jtxtAmountConverted.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtAmountConverted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAmountConvertedActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtAmountConverted, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 570, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 890, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 20));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel1.setText("Currency Converter");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 20));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Amount");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("From Currency");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("To Currency");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jtxtAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(jtxtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 550, -1));

        jToCurrency.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GBP - Britan", "CAD - Canadian Dollar", "USD - United States Dollar", "NGN - Nigerian Naria", "MXM - Mexican Peso", "EUR - Euro", "CHF - Swiss Franc", "AUD - Australian", "CNY - Chinese Yen", "INR - Indian Rupee", "ZMK - Zambian ", " ", " " }));
        jPanel3.add(jToCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 550, 40));

        jFromCurrency.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jFromCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GBP - Britan", "CAD - Canadian Dollar", "USD - United States Dollar", "NGN - Nigerian Naria", "MXM - Mexican Peso", "EUR - Euro", "CHF - Swiss Franc", "AUD - Australian", "CNY - Chinese Yen", "INR - Indian Rupee", "ZMK - Zambian ", " ", " ", " " }));
        jPanel3.add(jFromCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 550, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 890, 260));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 20));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 120, 40));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GBP - Britan", "CAD - Canadian Dollar", "USD - United States Dollar", "NGN - Nigerian Naria", "MXM - Mexican Peso", "EUR - Euro", "CHF - Swiss Franc", "AUD - Australian", "CNY - Chinese Yen", "INR - Indian Rupee", " ", " ", " " }));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 550, 40));

        jbtnConverter1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnConverter1.setText("Converter ");
        jbtnConverter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConverter1ActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnConverter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Exit ");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 890, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtAmount.setText("");
        jtxtAmountConverted.setText("");
        jFromCurrency.setSelectedIndex(-1);  
        jToCurrency.setSelectedIndex(-1);
    }//GEN-LAST:event_jbtnResetActionPerformed

//=========================================================================================
public double convertCurrency(double amount, String fromCurrency, String toCurrency ) {

    Map<String, Double> conversionRate = new HashMap<>();
    conversionRate.put("GBP", 1.0);
    conversionRate.put("CAD", 1.78);
    conversionRate.put("NGN", 1674.54);
    conversionRate.put("MXN", 29.39);
    conversionRate.put("EUR", 1.35);
    conversionRate.put("CHF", 1.45);
    conversionRate.put("AUD", 1.89);
    conversionRate.put("CNY", 9.09);
    conversionRate.put("INR", 107.93);
    conversionRate.put("USD", 1.57);
    conversionRate.put("ZMK", 33.76);
    conversionRate.put("JORDYN", 69.69);

    

    if (!conversionRate.containsKey (fromCurrency) || !conversionRate.containsKey(toCurrency)) {
        throw new IllegalArgumentException ("Invalid Currency Code.");
}

    return amount * conversionRate.get(toCurrency) / conversionRate.get(fromCurrency);

}




    private void jbtnConverter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConverter1ActionPerformed

        try {
            double amount = Double.parseDouble(jtxtAmount.getText());
            String fromCurrency = jFromCurrency.getSelectedItem().toString().substring(0, 3);
            String toCurrency = jToCurrency.getSelectedItem().toString().substring(0, 3);

            double convertAmount = convertCurrency(amount, fromCurrency, toCurrency);
            jtxtAmountConverted.setText(amount + " " + fromCurrency + " = " + convertAmount + " " + toCurrency);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Number", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    

    }//GEN-LAST:event_jbtnConverter1ActionPerformed


    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
                                         
    JFrame frame = new JFrame("Exit");
    if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Currency Converter", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
}  
               
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtAmountConvertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAmountConvertedActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jtxtAmountConvertedActionPerformed

   
    public void main(String args[]) {
     
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                          new JCurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jFromCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jToCurrency;
    private javax.swing.JButton jbtnConverter1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtAmountConverted;
    // End of variables declaration//GEN-END:variables

